[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
VITE_DOMAIN = "forgewright.io"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.github.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.github.com https://gutendex.com; font-src 'self' data:;"
Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), vr=(), accelerometer=(), gyroscope=(), magnetometer=(), fullscreen=(self)"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "*.woff2"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "font/woff2"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "*.woff"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "font/woff"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "*.ico"

[headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "image/x-icon"

[[headers]]
for = "*.png"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "*.jpg"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "*.svg"

[headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "image/svg+xml"

[[headers]]
for = "/manifest.json"

[headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "application/manifest+json"

[[redirects]]
from = "/app"
to = "/index.html"
status = 200

[[redirects]]
from = "/app/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/docs"
to = "/index.html"
status = 200

[[redirects]]
from = "/docs/*"
to = "/index.html"
status = 200

# API redirects for GitHub OAuth
[[redirects]]
from = "/auth/github"
to = "/index.html"
status = 200

[[redirects]]
from = "/auth/github/callback"
to = "/index.html"
status = 200

# Fallback for SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200